workflows:
  simple-android-build:
    name: Simple Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Set up Android SDK
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build AAB
        script: ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.aab
